version: 2.1
jobs:
  build image:
    docker:
      - image: cimage/go:1.17
    steps:
      - checkout 
      - setup_remote_docker
      - run:
          name: build docker image
          command:
            dicker build --tag=rab7a:${CIRCLE_BUILD_NUM} .

workflows:
  docker:
    jobs:
      - build image
      